AA_hydrophobic:list = ['A', 'V', 'I', 'L', 'M', 'F', 'W', ]
AA_polar_neutral:list = ['N', 'Q', 'S', 'T', 'Y']
AA_acidic:list = ['D', 'E']
AA_basic:list = ['R', 'H', 'K']
AA_list:list = ['A', 'V', 'I', 'L', 'M', 'F', 'W','N', 'Q', 'S', 'T', 'Y','D', 'E','R', 'H', 'K', 'C', 'P', 'G' ]